#¿Qué errores encuentras en este código?
j=input("numero: ")
for class in range(1,5,-1):
    print(class+j)


#EL FALLO QUE ENCUENTRO EN ESTE EJERCICIO ES LA IDENTACION BAJO EL FOR, YA QUE NO ESTÁ CORRECTA, SIENDO PYTHON UN
#LENGUAJE IDENTADO,ADEMÁS, LA CLASE NO SE HA DEFINIDO EN NINGUN MOMENTO