#ESCRIBE UN PROGRAMA QUE PERMITA CREAR UNA LISTA DE PALABRAS
#PARA ELLO PRIMERO SE PEDIRA UN NUMERO Y LUEGO PIDE
#LAS PALABRAS QUE SE QUIERA PARA LUEGO IMPRIMIR PALABRA POR PALABRA

numero = int(input("Escribe un numero: "))
lista=[] #CREAR NUEVA LISTA 
for i in range(numero): #SE CREA UN BUCLE CON AUMENTO Y PARADA HASTA EL NUMERO INTRODUCIDO, AQUI SE UTILIZA I DENTRO DEL RANGO DE NUMEROS INTRODUCIDO EN EL INPUT
    #print ("Quedan", numero-i, "Palabras por introducir") --> MUESTRO CUANTAS PALABRAS QUEDAN POR ESCRIBIR
    palabra=input("Introduzca una palabra, quedan " +str(numero-i)+ " palabras: ") #SE PIDE LA PALABRA y SE INDICAN A LA VEZ EL NUMERO DE PALABRAS QUE QUEDAN POR ESCRIBIR, SE CONVIERTE CON STR LA RESTA DEL NUMERO TOTAL - LA I QUE SE ENCUENTRA EN ESE MOMENTO EN EL BUCLE Y SE CONCATENA CON +
    lista.append(palabra)
for x in lista: #AQUI LO QUE SE HACE ES COGER CADA COMPONENTE DE LA LISTA Y MOSTRARLOS
    print(x)
    


        